name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{secrets.RESPOSITORY}}
          token: ${{secrets.PAT}}
          path: 'fd'
          
      - name: build macos arm64_x86_64
        run: |
          mkdir macos_arm64_x86_64
          mkdir macos_arm64_x86_64/macos_arm64
          mkdir macos_arm64_x86_64/macos_x86_64
          cd fd
          make clean
          make PP=g++ \
               CC=gcc \
               CFLAGS="-arch x86_64 -mmacosx-version-min=12.0" \
               LFLAGS="-arch x86_64 -mmacosx-version-min=12.0 -Wl,-Bsymbolic-functions" static
          cp bin/libfd.a ../macos_arm64_x86_64/macos_x86_64/libfd.a
          
          make clean
          make clean
          make PP=g++ \
               CC=gcc \
               CFLAGS="-arch arm64 -mmacosx-version-min=12.0" \
               LFLAGS="-arch arm64 -mmacosx-version-min=12.0 -Wl,-Bsymbolic-functions" static
          cp bin/libfd.a ../macos_arm64_x86_64/macos_arm64/libfd.a

          cd ../macos_arm64_x86_64
          lipo -create -o ./libfd.a ./macos_arm64/libfd.a ./macos_x86_64/libfd.a
      
      - name: Build xcframework
        run: |
          mkdir include
          cp fd/fd.h include/fd.h
          cp ./Templates/module.template include/module.modulemap
          xcodebuild -create-xcframework \
                     -library ./macos_arm64_x86_64/libfd.a \
                     -headers ./include \
                     -output ./FDKit.xcframework
          zip -r FDKit.xcframework.zip FDKit.xcframework
          
      - name: Rende Template
        run: |
          export TEMP=`shasum -a 256 ./FDKit.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          cd Templates
          sed -i "_bak" "s/VERSION/${{ github.event.inputs.version }}/g" Package.template
          sed -i "_bak" "s/CHECKSUM/${CHECKSUM}/g" Package.template
          
      - name: Update Package.swift
        run: |
          rm -f Package.swift
          cp ./Templates/Package.template Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: FDKit Release ${{ github.event.inputs.version }}!!!
          commit_user_name: Arror
          commit_user_email: hallo.maqiang@icloud.com
          commit_author: Arror <hallo.maqiang@icloud.com>
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: ./FDKit.xcframework.zip

